export const translations = {
    en: {
        dashboard: "Dashboard",
        calendar: "Calendar",
        appointments: "Appointments",
        customers: "Customers",
        services: "Services",
        barbers: "Barbers",
        shops: "Shops",
        profile: "Profile",
        logout: "Log Out",
        daily_planning: "Daily Planning",
        calendar_daily: "Daily Calendar",
        daily_global_calendar: "Daily Global Calendar",
        global_day_view: "Global Day View",
        global_day_view_desc: "Manage all your barbers at once.",
        horizontal: "Horizontal",
        vertical: "Vertical",
        welcome: "Welcome",
        total_revenue: "Total Revenue",
        monthly_revenue: "Monthly Revenue",
        total_customers: "Total Customers",
        total_appointments: "Total Appointments",
        top_barbers: "Top Barbers",
        recent_appointments: "Recent Appointments",
        search: "Search",
        book_appointment: "Book Appointment",
        add_barber: "Add New Barber",
        edit_barber: "Edit Barber",
        create_barber: "Create Barber",
        update_barber: "Update Barber",
        delete_barber: "Delete Barber",
        name: "Name",
        email: "Email",
        password: "Password",
        commission: "Commission",
        commission_type: "Commission Type",
        value: "Value",
        actions: "Actions",
        cancel: "Cancel",
        delete: "Delete",
        edit: "Edit",
        our_barbers: "Our Barbers",
        no_barbers_found: "No barbers found.",
        percentage: "Percentage (%)",
        fixed: "Fixed Amount ($)",
        confirm_delete_barber: "Are you sure you want to delete this barber?",
        failed_delete_barber: "Failed to delete barber.",
        error_occurred: "An error occurred. Please try again.",
        barber_name: "Barber Name",
        leave_blank_password: "Leave blank to keep current",
        secret_password: "Secret Password",
        appointment_details: "Appointment Details",
        barber: "Barber",
        customer: "Customer",
        time: "Time",
        status: "Status",
        estimated_price: "Estimated Price",
        close: "Close",
        complete_and_collect: "Complete & Collect",
        confirm_mark_as: "Are you sure you want to mark this appointment as ",
        error_updating_status: "Error updating status",
        failed_move_appointment: "Failed to move appointment: ",
        // Customers
        search_customers: "Search customers...",
        add_customer: "Add New Customer",
        phone: "Phone",
        last_visit: "Last Visit",
        never: "Never",
        no_customers_found: "No customers found.",
        edit_customer: "Edit Customer",
        create_customer: "Create Customer",
        update_customer: "Update Customer",
        customer_name: "Customer Name",
        phone_number: "Phone Number",
        notes: "Notes",
        confirm_delete_customer: "Are you sure you want to delete this customer?",
        failed_delete_customer: "Failed to delete customer.",
        // Services
        service_menu: "Service Menu",
        add_service: "Add New Service",
        duration: "Duration",
        price: "Price",
        extra_service: "Extra Service",
        mins_short: "mins",
        no_services_found: "No services found.",
        edit_service: "Edit Service",
        create_service: "Create Service",
        update_service: "Update Service",
        service_name: "Service Name",
        service_placeholder: "e.g. Haircut",
        duration_mins: "Duration (mins)",
        price_currency: "Price ($)",
        is_extra_label: "Is this an 'Extra' service? (e.g. Beard Trim add-on)",
        confirm_delete_service: "Are you sure you want to delete this service?",
        failed_delete_service: "Failed to delete service.",
        // Booking
        select_barber: "Select a Barber",
        start_time: "Start Time",
        select_existing: "Select Existing",
        create_new: "Create New",
        search_existing_customer: "Search Existing Customer",
        search_placeholder_short: "Start typing name or phone...",
        selected_label: "Selected:",
        change: "Change",
        name_placeholder: "John Doe",
        phone_placeholder: "+1 234 567 8900",
        duration_label: "Duration:",
        total_label: "Total:",
        booking_progress: "Booking...",
        confirm_booking: "Confirm Booking",
        complete_and_pay: "Complete & Pay",
        scheduled: "Scheduled",
        total_price: "Total Price",
        failed_update_status: "Failed to update status.",
        // Dashboard Extra
        owner_dashboard: "Owner Dashboard",
        this_month: "This Month",
        current_month_earnings: "Current month earnings",
        all_time: "All time",
        lifetime_bookings: "Lifetime bookings",
        view_all: "View All",
        revenue_trend: "Revenue Trend (Last 6 Months)",
        no_revenue_data: "No revenue data available yet.",
        top_performers: "Top Performers",
        no_performance_data: "No performance data yet.",
        view_calendar: "View Calendar",
        date: "Date",
        shop_calendar: "Shop Calendar",
        manage_barbers: "Manage Barbers",
        barber_management: "Barber Management",
        manage_customers: "Manage Customers",
        customer_management: "Customer Management",
        manage_services: "Manage Services",
        service_management: "Service Management",
        // Barber Dashboard
        barber_dashboard: "Barber Dashboard",
        my_dashboard: "My Dashboard",
        appointments_today: "Appointments Today",
        upcoming: "Upcoming",
        commission_this_month: "Commission (This Month)",
        total_earned: "Total Earned",
        lifetime: "Lifetime",
        commission_trend: "Commission Trend (This Month)",
        daily_commission_label: "Daily Commission ($)",
        no_commission_data: "No commission data for this month yet.",
        next_appointments: "Next Appointments",
        no_upcoming_scheduled: "No upcoming appointments scheduled.",
        my_appointments: "My Appointments",
        log_in: "Log in",
        remember_me: "Remember me",
        forgot_password: "Forgot your password?",
        register: "Register",
        shop_name_label: "Shop Name",
        confirm_password: "Confirm Password",
        already_registered: "Already registered?",
        // New Premium UI
        main_menu: "Main Menu",
        overview: "Overview",
        welcome_back: "Welcome Back",
        welcome_back_desc: "Enter your credentials to access your dashboard.",
        good_morning: "Good Morning",
        good_afternoon: "Good Afternoon",
        good_evening: "Good Evening",
        shop_status_desc: "Here's what's happening in your shop today.",
        barber_status_desc: "Ready for your next masterpiece?",
        total_basis: "Total Basis",
        earnings: "Earnings",
        revenue: "Revenue",
        barber_panel: "Barber Panel",
        pipeline: "Pipeline",
        today: "Today",
        upcoming_appointments: "Upcoming Appointments",
        open_calendar: "Open Calendar",
        scheduled_time: "Scheduled Time",
        price_label: "Price",
        bills: "Bills",
        add_bill: "Add Bill",
        bill_type: "Type",
        bill_amount: "Amount",
        bill_note: "Note",
        expenses: "Expenses",
        net_profit: "Net Profit",
        confirm_delete_bill: "Are you sure you want to delete this bill?",
        failed_delete_bill: "Failed to delete bill.",
        all_expenses: "All Expenses",
        no_bills_found: "No bills found.",
        manage_barbers_desc: "Manage your team of barbers and their commissions.",
        manage_services_desc: "Define the services and prices offered in your shop.",
        manage_bills_desc: "Track your shop expenses and utility costs.",
        filter_by_barber: "Filter by Barber",
        all_barbers: "All Barbers",
        week: "Week",
        day: "Day",
        list: "List",
        today: "Today",
        live_calendar: "Live Calendar",
        add_bills_to_track_expenses: "Add bills to track your shop's expenses.",
        add_your_first_bill: "Add your first bill",
        add_optional_note: "Add an optional note...",
        completed: "Completed",
        cancelled: "Cancelled",
        scheduled: "Scheduled",
        no_services_desc: "Create services to show them in your booking menu.",
        add_your_first_service: "Add your first service",
        try_adjusting_search: "Try adjusting your search or add a new customer.",
        add_your_first_customer: "Add your first customer",
        no_phone: "No phone",
        no_appointments_found: "No appointments found.",
        view_full_calendar: "View Full Calendar",
        view_all_appointments: "View All Appointments",
        gross_revenue: "Gross Revenue",
        shop_share: "Shop Share",
        after_commission: "(After Commission)",
        after_expenses: "(After Expenses)",
        commission_liability: "Barber Shares",
        top_services: "Top Services",
        this_week: "This Week",
        filtered_period: "Filtered Period",
        utility: "Utility",
        rent: "Rent",
        supplies: "Supplies",
        equipment: "Equipment",
        other: "Other",
        error_occurred: "An error occurred.",
        payouts: "Payouts",
        barber_payouts: "Barber Payouts",
        payout_management: "Payout Management",
        manage_payouts_desc: "Track and manage payments given to your barbers.",
        add_payout: "Add Payout",
        confirm_delete_payout: "Are you sure you want to delete this payout record?",
        no_payouts_found: "No payouts found.",
        add_payouts_to_track_expenses: "Add payouts to track money given to your barbers.",
        add_your_first_payout: "Add your first payout",
        amount: "Amount",
        clear_filters: "Clear Filters",
        reports: "Reports",
        barber_report: "Barber Report",
        generate_report: "Generate Report",
        total_services_value: "Total Services Value",
        total_commission_earned: "Total Commission Earned",
        total_payouts_received: "Total Payouts Received",
        outstanding_balance: "Outstanding Balance",
        appointments_list: "Appointments List",
        payouts_list: "Payouts List",
        start_date: "Start Date",
        end_date: "End Date",
        commission_value: "Commission Value",
        select_barber_dates_desc: "Select a barber and a date range to generate a performance and payout report.",
        all_statuses: "All Statuses",
        all_types: "All Types",
        date_time: "Date & Time",
        try_different_filters: "Try adjusting your filters to find what you're looking for.",
        est_share: "Est. Share",
        new_customers: "New Customers",
        total: "Total",
        recent_activity: "Recent Activity",
        appointment_management: "Appointment Management",
        pending: "Pending",
        no_note: "No note",
        note: "Note",
        weekly_revenue: "Weekly Revenue",
        daily_revenue: "Daily Revenue",
        walk_in: "Walk-in",
        no_address: "No Address",
        super_admin_dashboard: "Super Admin Dashboard",
        save: "Save",
        confirm: "Confirm",
        semi_paid: "Semi-Paid",
        unpaid: "Pending",
        paid: "Paid",
        finish_and_collect: "Finish & Collect",
        payment_status: "Payment Status",
        edit_appointment: "Edit Appointment",
        all_payment_statuses: "All Payment Statuses",
        select_services: "Select Services",
        search_services: "Search services...",
        delete: "Delete",
        confirm_delete_appointment: "Are you sure you want to delete this appointment?",
        error_deleting_appointment: "Error deleting appointment.",
        update_payment: "Update Payment",
        specify_type: "Specify Type",
        specify_type_placeholder: "e.g. Market, Repair...",
    },
    fr: {
        dashboard: "Tableau de Bord",
        calendar: "Calendrier",
        appointments: "Rendez-vous",
        customers: "Clients",
        services: "Services",
        barbers: "Coiffeurs",
        shops: "Boutiques",
        profile: "Profil",
        logout: "Se Déconnecter",
        daily_planning: "Planning Journalier",
        calendar_daily: "Calendrier Journalier",
        daily_global_calendar: "Calendrier Global Journalier",
        global_day_view: "Vue Globale de la Journée",
        global_day_view_desc: "Gérez tous vos coiffeurs en une seule fois.",
        horizontal: "Horizontal",
        vertical: "Vertical",
        welcome: "Bienvenue",
        total_revenue: "Revenu Total",
        monthly_revenue: "Revenu Mensuel",
        total_customers: "Clients Totaux",
        total_appointments: "Rendez-vous Totaux",
        top_barbers: "Meilleurs Coiffeurs",
        recent_appointments: "Rendez-vous Récents",
        search: "Rechercher",
        book_appointment: "Prendre Rendez-vous",
        add_barber: "Ajouter un Coiffeur",
        edit_barber: "Modifier le Coiffeur",
        create_barber: "Créer le Coiffeur",
        update_barber: "Mettre à jour",
        delete_barber: "Supprimer",
        name: "Nom",
        email: "Email",
        password: "Mot de passe",
        commission: "Commission",
        commission_type: "Type de Commission",
        value: "Valeur",
        actions: "Actions",
        cancel: "Annuler",
        delete: "Supprimer",
        edit: "Modifier",
        our_barbers: "Nos Coiffeurs",
        no_barbers_found: "Aucun coiffeur trouvé.",
        percentage: "Pourcentage (%)",
        fixed: "Montant Fixe ($)",
        confirm_delete_barber: "Êtes-vous sûr de vouloir supprimer ce coiffeur ?",
        failed_delete_barber: "Échec de la suppression du coiffeur.",
        error_occurred: "Une erreur est survenue. Veuillez réessayer.",
        barber_name: "Nom du Coiffeur",
        leave_blank_password: "Laisser vide pour conserver l'actuel",
        secret_password: "Mot de passe secret",
        appointment_details: "Détails du Rendez-vous",
        barber: "Coiffeur",
        customer: "Client",
        time: "Heure",
        status: "Statut",
        estimated_price: "Prix Estimé",
        close: "Fermer",
        complete_and_collect: "Terminer & Encaisser",
        confirm_mark_as: "Êtes-vous sûr de vouloir marquer ce rendez-vous comme ",
        error_updating_status: "Erreur lors de la mise à jour du statut",
        failed_move_appointment: "Échec du déplacement du rendez-vous : ",
        // Customers
        search_customers: "Rechercher des clients...",
        add_customer: "Ajouter un Client",
        phone: "Téléphone",
        last_visit: "Dernière Visite",
        never: "Jamais",
        no_customers_found: "Aucun client trouvé.",
        edit_customer: "Modifier le Client",
        create_customer: "Créer le Client",
        update_customer: "Mettre à jour",
        customer_name: "Nom du Client",
        phone_number: "Numéro de Téléphone",
        notes: "Notes",
        confirm_delete_customer: "Êtes-vous sûr de vouloir supprimer ce client ?",
        failed_delete_customer: "Échec de la suppression du client.",
        // Services
        service_menu: "Menu des Services",
        add_service: "Ajouter un Service",
        duration: "Durée",
        price: "Prix",
        extra_service: "Service Supplémentaire",
        mins_short: "mins",
        no_services_found: "Aucun service trouvé.",
        edit_service: "Modifier le Service",
        create_service: "Créer le Service",
        update_service: "Mettre à jour",
        service_name: "Nom du Service",
        service_placeholder: "ex. Coupe de cheveux",
        duration_mins: "Durée (mins)",
        price_currency: "Prix ($)",
        is_extra_label: "Est-ce un service 'Extra' ? (ex. Taille de barbe)",
        confirm_delete_service: "Êtes-vous sûr de vouloir supprimer ce service ?",
        failed_delete_service: "Échec de la suppression du service.",
        // Booking
        select_barber: "Sélectionner un Coiffeur",
        start_time: "Heure de Début",
        select_existing: "Sélectionner Existant",
        create_new: "Créer Nouveau",
        search_existing_customer: "Rechercher Client Existant",
        search_placeholder_short: "Tapez un nom ou tél...",
        selected_label: "Sélectionné :",
        change: "Changer",
        name_placeholder: "Jean Dupont",
        phone_placeholder: "+33 6 12 34 56 78",
        duration_label: "Durée :",
        total_label: "Total :",
        booking_progress: "Réservation...",
        confirm_booking: "Confirmer la Réservation",
        complete_and_pay: "Terminer & Payer",
        scheduled: "Prévu",
        total_price: "Prix Total",
        failed_update_status: "Échec de la mise à jour du statut.",
        // Dashboard Extra
        owner_dashboard: "Tableau de Bord Propriétaire",
        this_month: "Ce Mois",
        current_month_earnings: "Gains du mois en cours",
        all_time: "Tout le temps",
        lifetime_bookings: "Réservations totales",
        view_all: "Voir tout",
        revenue_trend: "Tendance des revenus (6 derniers mois)",
        no_revenue_data: "Aucune donnée de revenu disponible.",
        top_performers: "Meilleures Performances",
        no_performance_data: "Aucune donnée de performance.",
        view_calendar: "Voir le Calendrier",
        date: "Date",
        shop_calendar: "Calendrier de la Boutique",
        manage_barbers: "Gérer les Coiffeurs",
        barber_management: "Gestion des Coiffeurs",
        manage_customers: "Gérer les Clients",
        customer_management: "Gestion des Clients",
        manage_services: "Gérer les Services",
        service_management: "Gestion des Services",
        // Barber Dashboard
        barber_dashboard: "Tableau de Bord Coiffeur",
        my_dashboard: "Mon Tableau de Bord",
        appointments_today: "Rendez-vous Aujourd'hui",
        upcoming: "À venir",
        commission_this_month: "Commission (Ce Mois)",
        total_earned: "Total Gagné",
        lifetime: "Total (Vie)",
        commission_trend: "Évolution des Commissions (Ce Mois)",
        daily_commission_label: "Commission Quotidienne ($)",
        no_commission_data: "Aucune donnée de commission pour ce mois.",
        next_appointments: "Prochains Rendez-vous",
        no_upcoming_scheduled: "Aucun rendez-vous à venir prévu.",
        my_appointments: "Mes Rendez-vous",
        log_in: "Connexion",
        remember_me: "Se souvenir de moi",
        forgot_password: "Mot de passe oublié ?",
        register: "S'inscrire",
        shop_name_label: "Nom de la Boutique",
        confirm_password: "Confirmer le mot de passe",
        already_registered: "Déjà inscrit ?",
        // New Premium UI
        main_menu: "Menu Principal",
        overview: "Aperçu",
        welcome_back: "Bon retour",
        welcome_back_desc: "Entrez vos identifiants pour accéder à votre tableau de bord.",
        good_morning: "Bonjour",
        good_afternoon: "Bon après-midi",
        good_evening: "Bonsoir",
        shop_status_desc: "Voici ce qui se passe dans votre boutique aujourd'hui.",
        barber_status_desc: "Prêt pour votre prochain chef-d'œuvre ?",
        total_basis: "Base Totale",
        earnings: "Gains",
        revenue: "Revenu",
        barber_panel: "Panneau Coiffeur",
        pipeline: "Pipeline",
        today: "Aujourd'hui",
        upcoming_appointments: "Rendez-vous à venir",
        open_calendar: "Ouvrir le calendrier",
        scheduled_time: "Heure prévue",
        price_label: "Prix",
        bills: "Charges",
        add_bill: "Ajouter une charge",
        bill_type: "Type",
        bill_amount: "Montant",
        bill_note: "Note",
        expenses: "Dépenses",
        net_profit: "Bénéfice Net",
        confirm_delete_bill: "Êtes-vous sûr de vouloir supprimer cette charge ?",
        failed_delete_bill: "Échec de la suppression de la charge.",
        all_expenses: "Toutes les dépenses",
        no_bills_found: "Aucune charge trouvée.",
        manage_barbers_desc: "Gérez votre équipe de coiffeurs et leurs commissions.",
        manage_services_desc: "Définissez les services et les prix proposés dans votre boutique.",
        manage_bills_desc: "Suivez les dépenses de votre boutique et les coûts des services publics.",
        filter_by_barber: "Filtrer par Coiffeur",
        all_barbers: "Tous les Coiffeurs",
        week: "Semaine",
        day: "Jour",
        list: "Liste",
        today: "Aujourd'hui",
        live_calendar: "Calendrier en direct",
        add_bills_to_track_expenses: "Ajoutez des charges pour suivre les dépenses de votre boutique.",
        add_your_first_bill: "Ajouter votre première charge",
        add_optional_note: "Ajouter une note facultative...",
        completed: "Terminé",
        cancelled: "Annulé",
        scheduled: "Prévu",
        no_services_desc: "Créez des services pour les afficher dans votre menu de réservation.",
        add_your_first_service: "Ajouter votre premier service",
        try_adjusting_search: "Essayez d'ajuster votre recherche ou ajoutez un nouveau client.",
        add_your_first_customer: "Ajouter votre premier client",
        no_phone: "Pas de téléphone",
        no_appointments_found: "Aucun rendez-vous trouvé.",
        view_full_calendar: "Voir le Calendrier Complet",
        view_all_appointments: "Voir Tous les Rendez-vous",
        gross_revenue: "Chiffre d'Affaires Brut",
        shop_share: "Part Boutique",
        after_commission: "(Après Commission)",
        after_expenses: "(Après Dépenses)",
        commission_liability: "Parts Coiffeurs",
        top_services: "Meilleurs Services",
        this_week: "Cette Semaine",
        filtered_period: "Période Filtrée",
        utility: "Services publics",
        rent: "Loyer",
        supplies: "Fournitures",
        equipment: "Équipement",
        other: "Autre",
        error_occurred: "Une erreur est survenue.",
        payouts: "Paiements",
        barber_payouts: "Paiements des Coiffeurs",
        payout_management: "Gestion des Paiements",
        manage_payouts_desc: "Suivez et gérez les paiements versés à vos coiffeurs.",
        add_payout: "Ajouter un Paiement",
        confirm_delete_payout: "Êtes-vous sûr de vouloir supprimer cet enregistrement de paiement ?",
        no_payouts_found: "Aucun paiement trouvé.",
        add_payouts_to_track_expenses: "Ajoutez des paiements pour suivre l'argent donné à vos coiffeurs.",
        add_your_first_payout: "Ajouter votre premier paiement",
        amount: "Montant",
        clear_filters: "Effacer les Filtres",
        reports: "Rapports",
        barber_report: "Rapport Coiffeur",
        generate_report: "Générer le Rapport",
        total_services_value: "Valeur Totale des Services",
        total_commission_earned: "Total des Commissions Gagnées",
        total_payouts_received: "Total des Paiements Reçus",
        outstanding_balance: "Solde Restant",
        appointments_list: "Liste des Rendez-vous",
        payouts_list: "Liste des Paiements",
        start_date: "Date de Début",
        end_date: "Date de Fin",
        commission_value: "Valeur de la Commission",
        select_barber_dates_desc: "Sélectionnez un coiffeur et une plage de dates pour générer un rapport de performance et de paiement.",
        all_statuses: "Tous les Statuts",
        all_types: "Tous les Types",
        date_time: "Date & Heure",
        try_different_filters: "Essayez d'ajuster vos filtres pour trouver ce que vous cherchez.",
        est_share: "Part Est.",
        new_customers: "Nouveaux Clients",
        total: "Total",
        recent_activity: "Activité Récente",
        appointment_management: "Gestion des Rendez-vous",
        pending: "En attente",
        no_note: "Pas de note",
        note: "Note",
        weekly_revenue: "Revenu Hebdomadaire",
        daily_revenue: "Revenu Quotidien",
        walk_in: "Client Sans RDV",
        no_address: "Pas d'adresse",
        super_admin_dashboard: "Tableau de Bord Super Admin",
        save: "Enregistrer",
        confirm: "Confirmer",
        semi_paid: "Semi-Payé",
        unpaid: "En attente",
        paid: "Payé",
        finish_and_collect: "Terminer & Encaisser",
        payment_status: "Statut du Paiement",
        edit_appointment: "Modifier le Rendez-vous",
        all_payment_statuses: "Tous les Statuts de Paiement",
        select_services: "Choisir les services",
        search_services: "Rechercher des services...",
        delete: "Supprimer",
        confirm_delete_appointment: "Êtes-vous sûr de vouloir supprimer ce rendez-vous ?",
        error_deleting_appointment: "Erreur lors de la suppression du rendez-vous.",
        update_payment: "Mettre à jour le paiement",
        specify_type: "Préciser le type",
        specify_type_placeholder: "ex. Marché, Réparation...",
    },
    ar: {
        dashboard: "لوحة التحكم",
        calendar: "التقويم",
        appointments: "المواعيد",
        customers: "العملاء",
        services: "الخدمات",
        barbers: "الحلاقون",
        shops: "المحلات",
        profile: "الملف الشخصي",
        logout: "تسجيل الخروج",
        daily_planning: "التخطيط اليومي",
        calendar_daily: "التقويم اليومي",
        daily_global_calendar: "التقويم اليومي الشامل",
        global_day_view: "عرض اليوم الشامل",
        global_day_view_desc: "إدارة جميع حلاقي المحل في وقت واحد.",
        horizontal: "أفقي",
        vertical: "عمودي",
        welcome: "مرحباً",
        total_revenue: "إجمالي الإيرادات",
        monthly_revenue: "الإيرادات الشهرية",
        total_customers: "إجمالي العملاء",
        total_appointments: "إجمالي المواعيد",
        top_barbers: "أفضل الحلاقين",
        recent_appointments: "المواعيد الأخيرة",
        search: "بحث",
        book_appointment: "حجز موعد",
        add_barber: "إضافة حلاق جديد",
        edit_barber: "تعديل الحلاق",
        create_barber: "إنشاء حلاق",
        update_barber: "تحديث الحلاق",
        delete_barber: "حذف الحلاق",
        name: "الاسم",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        commission: "العمولة",
        commission_type: "نوع العمولة",
        value: "القيمة",
        actions: "الإجراءات",
        cancel: "إلغاء",
        delete: "حذف",
        edit: "تعديل",
        our_barbers: "حلاقونا",
        no_barbers_found: "لم يتم العثور على حلاقين.",
        percentage: "نسبة مئوية (%)",
        fixed: "مبلغ ثابت ($)",
        confirm_delete_barber: "هل أنت متأكد من حذف هذا الحلاق؟",
        failed_delete_barber: "فشل حذف الحلاق.",
        error_occurred: "حدث خطأ. يرجى المحاولة مرة أخرى.",
        barber_name: "اسم الحلاق",
        leave_blank_password: "اتركه فارغاً للاحتفاظ بالحالي",
        secret_password: "كلمة مرور سرية",
        appointment_details: "تفاصيل الموعد",
        barber: "الحلاق",
        customer: "العميل",
        time: "الوقت",
        status: "الحالة",
        estimated_price: "السعر التقديري",
        close: "إغلاق",
        complete_and_collect: "إتمام وتحصيل",
        confirm_mark_as: "هل أنت متأكد من تحديد هذا الموعد كـ ",
        error_updating_status: "خطأ في تحديث الحالة",
        failed_move_appointment: "فشل نقل الموعد: ",
        // Customers
        search_customers: "بحث عن عملاء...",
        add_customer: "إضافة عميل جديد",
        phone: "الهاتف",
        last_visit: "آخر زيارة",
        never: "أبداً",
        no_customers_found: "لم يتم العثور على عملاء.",
        edit_customer: "تعديل العميل",
        create_customer: "إنشاء عميل",
        update_customer: "تحديث العميل",
        customer_name: "اسم العميل",
        phone_number: "رقم الهاتف",
        notes: "ملاحظات",
        confirm_delete_customer: "هل أنت متأكد من حذف هذا العميل؟",
        failed_delete_customer: "فشل حذف العميل.",
        // Services
        service_menu: "قائمة الخدمات",
        add_service: "إضافة خدمة جديدة",
        duration: "المدة",
        price: "السعر",
        extra_service: "خدمة إضافية",
        mins_short: "دقيقة",
        no_services_found: "لم يتم العثور على خدمات.",
        edit_service: "تعديل الخدمة",
        create_service: "إنشاء خدمة",
        update_service: "تحديث الخدمة",
        service_name: "اسم الخدمة",
        service_placeholder: "مثلاً: قص شعر",
        duration_mins: "المدة (بالدقائق)",
        price_currency: "السعر ($)",
        is_extra_label: "هل هذه خدمة 'إضافية'؟ (مثلاً: تهذيب اللحية)",
        confirm_delete_service: "هل أنت متأكد من حذف هذه الخدمة؟",
        failed_delete_service: "فشل حذف الخدمة.",
        // Booking
        select_barber: "اختر حلاقاً",
        start_time: "وقت البدء",
        select_existing: "اختر عميلاً موجوداً",
        create_new: "إنشاء جديد",
        search_existing_customer: "بحث عن عميل موجود",
        search_placeholder_short: "ابدأ بكتابة الاسم أو الهاتف...",
        selected_label: "المختار:",
        change: "تغيير",
        name_placeholder: "أحمد محمد",
        phone_placeholder: "+966 50 123 4567",
        duration_label: "المدة:",
        total_label: "الإجمالي:",
        booking_progress: "جاري الحجز...",
        confirm_booking: "تأكيد الحجز",
        complete_and_pay: "إتمام ودفع",
        scheduled: "مجدول",
        total_price: "السعر الإجمالي",
        failed_update_status: "فشل تحديث الحالة.",
        // Dashboard Extra
        owner_dashboard: "لوحة تحكم المالك",
        this_month: "هذا الشهر",
        current_month_earnings: "أرباح الشهر الحالي",
        all_time: "كل الوقت",
        lifetime_bookings: "إجمالي الحجوزات",
        view_all: "عرض الكل",
        revenue_trend: "اتجاه الإيرادات (آخر 6 أشهر)",
        no_revenue_data: "لا توجد بيانات إيرادات متاحة بعد.",
        top_performers: "الأفضل أداءً",
        no_performance_data: "لا توجد بيانات أداء بعد.",
        view_calendar: "عرض التقويم",
        date: "التاريخ",
        shop_calendar: "تقويم المحل",
        manage_barbers: "إدارة الحلاقين",
        barber_management: "إدارة الحلاقين",
        manage_customers: "إدارة العملاء",
        customer_management: "إدارة العملاء",
        manage_services: "إدارة الخدمات",
        service_management: "إدارة الخدمات",
        // Barber Dashboard
        barber_dashboard: "لوحة تحكم الحلاق",
        my_dashboard: "لوحة تحكمي",
        appointments_today: "مواعيد اليوم",
        upcoming: "القادمة",
        commission_this_month: "العمولة (هذا الشهر)",
        total_earned: "إجمالي الأرباح",
        lifetime: "مدى الحياة",
        commission_trend: "اتجاه العمولة (هذا الشهر)",
        daily_commission_label: "العمولة اليومية ($)",
        no_commission_data: "لا توجد بيانات عمولة لهذا الشهر بعد.",
        next_appointments: "المواعيد القادمة",
        no_upcoming_scheduled: "لا توجد مواعيد قادمة مجدولة.",
        my_appointments: "مواعيدي",
        log_in: "تسجيل الدخول",
        remember_me: "تذكرني",
        forgot_password: "نسيت كلمة المرور؟",
        register: "تسجيل",
        shop_name_label: "اسم المحل",
        confirm_password: "تأكيد كلمة المرور",
        already_registered: "مسجل بالفعل؟",
        // New Premium UI
        main_menu: "القائمة الرئيسية",
        overview: "نظرة عامة",
        welcome_back: "مرحباً بعودتك",
        welcome_back_desc: "أدخل بيانات الاعتماد الخاصة بك للوصول إلى لوحة التحكم الخاصة بك.",
        good_morning: "صباح الخير",
        good_afternoon: "مساء الخير",
        good_evening: "مساء الخير",
        shop_status_desc: "إليك ما يحدث في محلك اليوم.",
        barber_status_desc: "هل أنت مستعد لإبداعك القادم؟",
        total_basis: "الأساسي الإجمالي",
        earnings: "الأرباح",
        revenue: "الإيرادات",
        barber_panel: "لوحة الحلاق",
        pipeline: "قيد التنفيذ",
        today: "اليوم",
        upcoming_appointments: "المواعيد القادمة",
        open_calendar: "افتح التقويم",
        scheduled_time: "الوقت المجدول",
        price_label: "السعر",
        bills: "المصاريف",
        add_bill: "إضافة مصاريف",
        bill_type: "النوع",
        bill_amount: "المبلغ",
        bill_note: "ملاحظة",
        expenses: "المصروفات",
        net_profit: "صافي الأرباح",
        confirm_delete_bill: "هل أنت متأكد من حذف هذه المصاريف؟",
        failed_delete_bill: "فشل حذف المصاريف.",
        all_expenses: "كل المصروفات",
        no_bills_found: "لم يتم العثور على مصاريف.",
        manage_barbers_desc: "إدارة فريق الحلاقين الخاص بك وعمولاتهم.",
        manage_services_desc: "حدد الخدمات والأسعار المقدمة في محلك.",
        manage_bills_desc: "تتبع مصاريف محلك وتكاليف المرافق.",
        filter_by_barber: "تصفية حسب الحلاق",
        all_barbers: "كل الحلاقين",
        week: "أسبوع",
        day: "يوم",
        list: "قائمة",
        today: "اليوم",
        live_calendar: "التقويم المباشر",
        add_bills_to_track_expenses: "أضف المصاريف لتتبع نفقات محلك.",
        add_your_first_bill: "أضف أول مصروفاتك",
        add_optional_note: "أضف ملاحظة اختيارية...",
        completed: "مكتمل",
        cancelled: "ملغي",
        scheduled: "مجدول",
        no_services_desc: "أنشئ خدمات لعرضها في قائمة الحجز الخاصة بك.",
        add_your_first_service: "أضف خدمتك الأولى",
        try_adjusting_search: "حاول تعديل بحثك أو أضف عميلاً جديداً.",
        add_your_first_customer: "أضف عميلك الأول",
        no_phone: "لا يوجد هاتف",
        no_appointments_found: "لم يتم العثور على مواعيد.",
        view_full_calendar: "عرض التقويم الكامل",
        view_all_appointments: "عرض جميع المواعيد",
        gross_revenue: "إجمالي الإيرادات",
        shop_share: "حصة المحل",
        after_commission: "(بعد العمولات)",
        after_expenses: "(بعد المصاريف)",
        commission_liability: "مستحقات الحلاقين",
        top_services: "أفضل الخدمات",
        this_week: "هذا الأسبوع",
        filtered_period: "الفترة المختارة",
        utility: "المرافق",
        rent: "الإيجار",
        supplies: "المستلزمات",
        equipment: "المعدات",
        other: "أخرى",
        error_occurred: "حدث خطأ ما.",
        payouts: "الدفعات",
        barber_payouts: "دفعات الحلاقين",
        payout_management: "إدارة الدفعات",
        manage_payouts_desc: "تتبع وإدارة المبالغ المالية المعطاة للحلاقين.",
        add_payout: "إضافة دفعة",
        confirm_delete_payout: "هل أنت متأكد من حذف سجل هذه الدفعة؟",
        no_payouts_found: "لم يتم العثور على دفعات.",
        add_payouts_to_track_expenses: "أضف الدفعات لتتبع الأموال المعطاة للحلاقين.",
        add_your_first_payout: "أضف دفعتك الأولى",
        amount: "المبلغ",
        clear_filters: "مسح الفلاتر",
        reports: "التقارير",
        barber_report: "تقرير الحلاق",
        generate_report: "إنشاء التقرير",
        total_services_value: "إجمالي قيمة الخدمات",
        total_commission_earned: "إجمالي العمولات المكتسبة",
        total_payouts_received: "إجمالي الدفعات المستلمة",
        outstanding_balance: "الرصيد المتبقي",
        appointments_list: "قائمة المواعيد",
        payouts_list: "قائمة الدفعات",
        start_date: "تاريخ البدء",
        end_date: "تاريخ الانتهاء",
        commission_value: "قيمة العمولة",
        select_barber_dates_desc: "اختر حلاقاً ونطاقاً زمنياً لإنشاء تقرير الأداء والدفعات.",
        all_statuses: "جميع الحالات",
        all_types: "جميع الأنواع",
        date_time: "التاريخ والوقت",
        try_different_filters: "جرّب تعديل الفلاتر للعثور على ما تبحث عنه.",
        est_share: "الحصة التقديرية",
        new_customers: "عملاء جدد",
        total: "الإجمالي",
        recent_activity: "آخر الأنشطة",
        appointment_management: "إدارة المواعيد",
        pending: "قيد الانتظار",
        no_note: "لا توجد ملاحظة",
        note: "ملاحظة",
        weekly_revenue: "الإيرادات الأسبوعية",
        daily_revenue: "الإيرادات اليومية",
        walk_in: "عميل عابر",
        no_address: "لا يوجد عنوان",
        super_admin_dashboard: "لوحة تحكم المسؤول العام",
        save: "حفظ",
        confirm: "تأكيد",
        semi_paid: "مدفوع جزئياً",
        unpaid: "قيد الانتظار",
        paid: "مدفوع",
        finish_and_collect: "إنهاء وتحصيل",
        payment_status: "حالة الدفع",
        edit_appointment: "تعديل الموعد",
        all_payment_statuses: "جميع حالات الدفع",
        select_services: "اختر الخدمات",
        search_services: "ابحث عن الخدمات...",
    }
};

export function trans(key, locale = 'en') {
    return translations[locale]?.[key] || key;
}
